#!/bin/bash

. media_common.sh

LOG=encoding.log

# create log file
if [ ! -f "$LOG" ]; then
	> $LOG
fi
exec 1>$LOG

if [ ! -f "wordpress.conf" ]; then
	log "Missing WordPress credentials"
	exit 0
fi

EXECDIR=$(pwd)

# array of sites subdomains:folder
ARRAY=(
"missionviejo:RHMV"
"fullerton:RHF"
"huntingtonbeach:RHHB"
"orange:RHO"
)

PREFIX="/Volumes/Media/FTP/Messages"

for S in ${ARRAY[@]}; do
	SUBDOMAIN=${S%%:*}
	FOLDER=${S##*:}

	# watch these folders for FTP uploads, which are renamed, moved,
	# compressed and uploaded to WordPress
	log "Setting up watch on $PREFIX/$FOLDER for $SUBDOMAIN"
	watchmedo shell-command \
		--command=$EXECDIR'/process_media_file.sh "${watch_src_path}" "${watch_event_type}" "'$SUBDOMAIN'"' \
		"$PREFIX/$FOLDER" &
done
