#!/bin/bash

. media_common.sh

# create log file
if [ ! -f "$LOG" ]; then
	> $LOG
fi

if [ ! -f "credentials.conf" ]; then
	log "Missing credentials"
	exit 0
fi

. credentials.conf

EXECDIR="/encoder"

# array of sites subdomains:folder
ARRAY=(
"costamesa:RHC"
"missionviejo:RHMV"
"fullerton:RHF"
"huntingtonbeach:RHHB"
"orange:RHO"
)

PREFIX="/FTP"

STOREPATH="/MediaVault/FTP/Messages"

for S in ${ARRAY[@]}; do
	SUBDOMAIN=${S%%:*}
	FOLDER=${S##*:}

	# watch these folders for FTP uploads, which are renamed, moved,
	# compressed and uploaded to WordPress
	log "Setting up watch on $PREFIX/$FOLDER for $SUBDOMAIN"
	/usr/local/bin/watchmedo shell-command \
		--command=$EXECDIR'/process_media_file.sh "${watch_src_path}" "${watch_event_type}" "'$SUBDOMAIN'" "'$STOREPATH/$FOLDER'"' \
		"$PREFIX/$FOLDER" &
done

# make launchd happy
# http://developer.apple.com/library/mac/#documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html#//apple_ref/doc/uid/TP40001762-104142
sleep 10

exit 0
